version: '3.8'

services:
  api:
    image: api
    deploy:
        mode: replicated
        replicas: 10

  nginx: 
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - 3000:3000